site_name: RPG Wiki System
site_url: https://twoja-strona.com
theme:
  name: material
  language: pl
  palette: 
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Przełącz na tryb ciemny
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Przełącz na tryb jasny
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details

nav:
  - Strona główna: index.md
  - Spis treści: spis_tresci.md
  - Cień Władcy Demonów:
    - Przegląd: compendium/shadow_demon_lord/index.md
    - Pochodzenia:
      - Automaton: compendium/shadow_demon_lord/origins/automaton.md
      - Człowiek: compendium/shadow_demon_lord/origins/czlowiek.md
      - Goblin: compendium/shadow_demon_lord/origins/goblin.md
    - Ścieżki Eksperckie:
      - Wyrocznia: compendium/shadow_demon_lord/expert_paths/wyrocznia.md
    - Tradycje Magii:
      - Alchemia: compendium/shadow_demon_lord/magic_traditions/alchemia.md
      - Chaos: compendium/shadow_demon_lord/magic_traditions/chaos.md
      - Czas: compendium/shadow_demon_lord/magic_traditions/czas.md
      - Demonologia: compendium/shadow_demon_lord/magic_traditions/demonologia.md
      - Iluzja: compendium/shadow_demon_lord/magic_traditions/iluzja.md
      - Inkantacje: compendium/shadow_demon_lord/magic_traditions/inkantacje.md
      - Jasnowidzenie: compendium/shadow_demon_lord/magic_traditions/jasnowidzenie.md
      - Klątwy: compendium/shadow_demon_lord/magic_traditions/klatwy.md
      - Magia Bitewna: compendium/shadow_demon_lord/magic_traditions/magia_bitewna.md
      - Magia Burzy: compendium/shadow_demon_lord/magic_traditions/magia_burzy.md
      - Magia Cienia: compendium/shadow_demon_lord/magic_traditions/magia_cienia.md
      - Magia Fey: compendium/shadow_demon_lord/magic_traditions/magia_fey.md
      - Magia Krwi: compendium/shadow_demon_lord/magic_traditions/magia_krwi.md
      - Magia Niebiańska: compendium/shadow_demon_lord/magic_traditions/magia_niebianska.md
      - Magia Pierwotna: compendium/shadow_demon_lord/magic_traditions/magia_pierwotna.md
      - Magia Runiczna: compendium/shadow_demon_lord/magic_traditions/magia_runiczna.md
      - Natura: compendium/shadow_demon_lord/magic_traditions/natura.md
      - Nekromancja: compendium/shadow_demon_lord/magic_traditions/nekromancja.md
      - Ochrona: compendium/shadow_demon_lord/magic_traditions/ochrona.md
      - Ogień: compendium/shadow_demon_lord/magic_traditions/ogien.md
      - Pieśń: compendium/shadow_demon_lord/magic_traditions/piesn.md
      - Powietrze: compendium/shadow_demon_lord/magic_traditions/powietrze.md
      - Przemiany: compendium/shadow_demon_lord/magic_traditions/przemiany.md
      - Przywołania: compendium/shadow_demon_lord/magic_traditions/przywolania.md
      - Śmierć: compendium/shadow_demon_lord/magic_traditions/smierc.md
      - Spirytyzm: compendium/shadow_demon_lord/magic_traditions/spirytyzm.md
      - Sztuki Tajemne: compendium/shadow_demon_lord/magic_traditions/sztuki_tajemne.md
      - Sztuki Zakazane: compendium/shadow_demon_lord/magic_traditions/sztuki_zakazane.md
      - Technomancja: compendium/shadow_demon_lord/magic_traditions/technomancja.md
      - Telekineza: compendium/shadow_demon_lord/magic_traditions/telekineza.md
      - Telepatia: compendium/shadow_demon_lord/magic_traditions/telepatia.md
      - Teleportacja: compendium/shadow_demon_lord/magic_traditions/teleportacja.md
      - Teurgia: compendium/shadow_demon_lord/magic_traditions/teurgia.md
      - Transformacja: compendium/shadow_demon_lord/magic_traditions/transformacja.md
      - Uroki: compendium/shadow_demon_lord/magic_traditions/uroki.md
      - Woda: compendium/shadow_demon_lord/magic_traditions/woda.md
      - Ziemia: compendium/shadow_demon_lord/magic_traditions/ziemia.md
      - Zniszczenie: compendium/shadow_demon_lord/magic_traditions/zniszczenie.md
      - Życie: compendium/shadow_demon_lord/magic_traditions/zycie.md